# Generated by Django 3.0.4 on 2020-04-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=64)),
                ('data', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(default='admin', max_length=32)),
                ('count_messages', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('main_text', models.CharField(max_length=500)),
            ],
        ),
    ]
